import { ThemeProvider } from "@/components/theme-provider";
import { fontSans } from "@/lib/fonts";
import { cn } from "@/lib/utils";

import "./globals.css";
import { SiteHeader } from "@/components/header";
import { ReactNode } from "react";

export const metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html className="" lang="de" suppressHydrationWarning>
      {/* Suppress input zooming on mobile devices. */}
      <meta
        content="width=device-width, initial-scale=1, maximum-scale=1, viewport-fit=cover"
        name="viewport"
      />
      <body
        className={cn(
          "min-h-screen bg-muted/40 font-sans antialiased",
          fontSans.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          disableTransitionOnChange
          enableSystem
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
