import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";
import { createCookie } from "./actions";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const state = cookieStore.get("state");

  console.log("the cookie state: ", JSON.parse(state.value));

  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
