import { cn } from "@/lib/utils"
import { Inter as FontSans } from "next/font/google"

import "./globals.css";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cn(
        "min-h-screen bg-background font-sans antialiased overflow-hidden",
        fontSans.variable
      )}>{children}</body>
    </html>
  );
}
